channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-celldex=1.16.0
  - bioconda::bioconductor-hdf5array=1.34.0
  - bioconda::bioconductor-singlecellexperiment=1.28.0
  - conda-forge::r-yaml=2.3.10
