[workspace]
authors = ["Aditya Singh <dr.singhaditya@hotmail.com>"]
channels = ["conda-forge"]
name = "gensheet"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.1,<3"
streamlit = ">=1.47.1,<2"
streamlit-aggrid = ">=1.1.7,<2"
